- hosts: ztest
  tasks:
    - name: install snapd
      ansible.builtin.package:
        name:
          - snapd
    - name: Install LXD 4.0
      community.general.snap:
        name: lxd
        channel: 4.0/stable

    - name: Add kubic repository key on Ubuntu.
      apt_key:
        url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_{{ ansible_distribution_version}}/Release.key
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "focal"

    - name: Add kubic repository on Ubuntu.
      apt_repository:
        repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ ansible_distribution_version}}/ /
        state: present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == "focal"


    - name:
      ansible.builtin.package:
        name:
          - podman
          - buildah
          - skopeo
          - slirp4netns

    - name: Set driver to zfs.
      lineinfile:
        path: /etc/containers/storage.conf
        regexp: ^driver
        line: driver = "zfs"
        insertafter: '^# Default Storage Driver'
    - shell: |
        lxd init --preseed << EOF
        config: {}
        networks:
        - config:
            ipv4.address: 10.211.202.254/24
            ipv4.nat: "true"
            ipv6.address: auto
          description: ""
          name: lxdbr0
          type: ""
        storage_pools:
        - config:
            source: tank/lxd
          description: ""
          name: default
          driver: zfs
        profiles:
        - config: {}
          description: ""
          devices:
            eth0:
              name: eth0
              network: lxdbr0
              type: nic
            root:
              path: /
              pool: default
              type: disk
          name: default
        cluster: null

        EOF
