packer {
  required_plugins {
    hcloud = {
      source  = "github.com/hetznercloud/hcloud"
      version = "~> 1"
    }
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
  }
}

variable "hcloud_token" {
    sensitive = true # Requires terraform >= 0.14
}

source "hcloud" "autogenerated_1" {
  image        = "ubuntu-22.04"
  location     = "nbg1"
  server_type  = "cx11"
  upgrade_server_type = "cx51"
  ssh_keys     = ["mykey"]
  ssh_username = "root"
  token        = "${var.hcloud_token}"
  rescue       = "linux64"
  snapshot_name = "universal-server-template"
  snapshot_labels = {
    "type" = "universal-server-template"
  }
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.hcloud.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "echo provisioning all the things",
    ]
  }

  provisioner "ansible" {
      playbook_file = "./ansible-packer.yml"
  }

}
